### ISSUE TITLE
pre-commit hook is not failing on lint errors

### ISSUE THREAD

**Issue by dylancwood** [MRN-Code/coinstac-common#5]
If I run `jscs src/**/*.js test/**/*.js` within this repo, I get a ton of errors and warnings. However, when `lint` is run by the pre-commit hook, it allows the commit to continue...

**Comment by cdaringe** [comment]
hmm. interesting.  i think it might be the globbing?  it's actually as expected for me.  i will remove the explicit globbing.  let's see if that does the trick

**Comment by cdaringe** [comment]
def is now!
